
version: '2'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: laravel-app
    container_name: app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'sample_app'
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
